name: Deploy constantin-saguin to SiteGround

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u806-3ucq2u3ym7q9/www/constantin.saguin.com/public_html/portfolio
            git pull origin master
            cp index.html ~/www/constantin.saguin.com/public_html/index.html
            cp style.css ~/www/constantin.saguin.com/public_html/style.css
            mkdir -p ~/www/constantin.saguin.com/public_html/img
            cp -r img/* ~/www/constantin.saguin.com/public_html/img/
            mkdir -p ~/www/constantin.saguin.com/public_html/js
            cp -r js/* ~/www/constantin.saguin.com/public_html/js/
            cd /home/u806-3ucq2u3ym7q9/www/constantin.saguin.com/public_html/
            curl -D - -sSX PURGE http://127.0.0.1/* -H "Host: constantin.saguin.com"
